[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
polygon = "${RPC_URL}"
polygon_amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137 }

[fuzz]
runs = 256
